- name: "Deploy {{ app_user }} Systemd Service File"
  template:
    src: service.j2
    dest: "{{ service_path }}/{{ app_user }}@.service"
    mode: 0775

- name: "Deploy {{ app_user }} Target Systemd Service File"
  template:
    src: service.target.j2
    dest: "{{ service_path }}/{{ app_user }}.target"
    mode: 0775

- name: "Deploy Environment Variables Empty File"
  template:
    src: integrark.j2
    dest: "/etc/opt/{{ app_user }}/{{ app_user }}.env"
    mode: 0644
    force: no

- name: "Restart {{ app_user }} Service"
  systemd:
    name: "{{ app_user }}.target"
    enabled: true
    state: restarted
    daemon_reload: true
